"""OmniScript syntax tree nodes.

Every node carries the line/column it started at so runtime errors can point
at the exact place in your source.
"""

from __future__ import annotations


class Node:
    """Base node. Subclasses are generated by `nodetype()` below."""

    fields: tuple[str, ...] = ()

    def __init__(self, *args, line: int = 0, col: int = 0, **kwargs):
        for name, value in zip(self.fields, args):
            setattr(self, name, value)
        for name, value in kwargs.items():
            if name not in self.fields:
                raise TypeError(f"{type(self).__name__} has no field `{name}`")
            setattr(self, name, value)
        for name in self.fields:
            if not hasattr(self, name):
                setattr(self, name, None)
        self.line = line
        self.col = col

    def __repr__(self):  # pragma: no cover - debug helper
        inner = ", ".join(f"{k}={getattr(self, k)!r}" for k in self.fields)
        return f"{type(self).__name__}({inner}) @{self.line}:{self.col}"


def nodetype(name: str, *fields: str):
    cls = type(name, (Node,), {"fields": fields})
    cls.__qualname__ = name
    globals()[name] = cls
    return cls


# ---------------------------------------------------------------- expressions
nodetype("Num", "value")
nodetype("Str", "chunks")                       # str | list[str | ("expr", tokens)]
nodetype("Bool", "value")
nodetype("Null")
nodetype("Ident", "name")
nodetype("SigAttr", "name")                     # @name -- namespace handle
nodetype("ListLit", "items", "spread")          # spread: parallel list[bool]
nodetype("MapLit", "entries")                   # list[(key_node_or_str, val_node, is_spread)]
nodetype("RangeLit", "lo", "hi", "step", "inclusive")
nodetype("Unary", "op", "operand")
nodetype("Binary", "op", "left", "right")
nodetype("Ternary", "cond", "then", "otherwise")
nodetype("Elvis", "left", "right")              # a ?? b
nodetype("Assign", "op", "target", "value")
nodetype("Index", "obj", "index")
nodetype("Slice", "obj", "lo", "hi", "step")
nodetype("Member", "obj", "name", "optional")
nodetype("Call", "callee", "args", "kwargs", "is_new")
nodetype("Pipe", "callee", "args", "kwargs", "all")
nodetype("Lambda", "params", "body", "is_block")
nodetype("If", "branches", "otherwise")         # branches: list[(cond, block)]
nodetype("Match", "subject", "arms")
nodetype("Block", "stmts", "is_expr")
nodetype("Paren", "inner")

# match patterns
nodetype("PLit", "value")
nodetype("PBind", "name")
nodetype("PWild")
nodetype("PList", "items", "rest")
nodetype("PMap", "entries")                     # list[(key, pattern)]
nodetype("PTyped", "name", "type", "neg")        # x is num / x isnt num

# ------------------------------------------------------------------ statements
nodetype("Let", "targets", "value", "mutable")
nodetype("FnDecl", "name", "params", "body", "attrs")
nodetype("ClassDecl", "name", "parent", "members", "attrs")
nodetype("For", "targets", "iterable", "body", "by")
nodetype("While", "cond", "body")
nodetype("DoWhile", "body", "cond")
nodetype("Try", "body", "catch_name", "catch_body", "finally_body")
nodetype("Return", "value")
nodetype("Throw", "value")
nodetype("Break")
nodetype("Continue")
nodetype("Use", "path", "alias", "names")
nodetype("ExprStmt", "expr")


class MatchArm(Node):
    fields = ("pattern", "guard", "value")
